### ISSUE TITLE
[Bug] Error with localizacion

### ISSUE THREAD

**Issue by lozalojo** [ardittristan/VTTReturnToSetup#4]
Seems that there is a duplicate entry for ReturnToSetup when localised.

![](https://i.ibb.co/r3Vyq83/screenshot-83.jpg)

**Comment by ardittristan** [comment]
does this also happen after you remove the Return to Setup player? since it names the player what the translation is named like. So if you load in english first it'll also create an english variant.

**Comment by lozalojo** [comment]
Looks like mixing languages is a very bad idea, the spanish translation "Volver a la Configuración" does not work, and I have removed "Return to Setup", but know I am stuck at the current world since "Volver a la Configuración" does not send me to the setup page, and keeps loggin in the current world.

I have to switch language to english, let the program create Return to setup and use that user to go to settings (and this way it works).

Not tested if a clean activation in spanish (not mixing languages) works as expected.

**Comment by ardittristan** [comment]
oh, I see I forgot to replace one "Return to Setup", oops, let me fix that and test

**Comment by ardittristan** [comment]
should be fixed with 1.0.7

**Comment by lozalojo** [comment]
Still not working.

Updated to 1.0.7
Brand new world.
Changed to Spanish.
Activate ReturnToSetup.
Logout.
Select player "Volver a Configuración" and enters the game, does not return to setup.

**Comment by ardittristan** [comment]
hm, it seems to work fine for me on both 0.6.6 and 0.7.3

I did notice that Castellano shows up twice, and only the second one works for me (it shows twice even with no modules active at all)
![image](https://user-images.githubusercontent.com/42787508/95608751-e1b67700-0a5d-11eb-9549-10e16de0780d.png)

**Comment by lozalojo** [comment]
It is a problem of the installation, with the client (local) it works, but with my server (a linux instance running ubuntu 20) does not work, same world.

BTW, how can be possible you have two spanish entries? is it dnd5?

**Comment by ardittristan** [comment]
is there any error in the console on the linux instance?

the double Castellano entry was because of a wrong config on 5e-resources-plus, which is fixed now.

**Comment by lozalojo** [comment]
I checked the log and no errors.

**Comment by ardittristan** [comment]
Then I have no clue why it wouldn't work, unless the language on the server is not set to Castellano. I can't really do anything about that since it's not possible to manipulate the login screen with modules so I can only hard-set the names in the languages selected by the DMs

**Comment by ardittristan** [comment]
Since the main problem is solved, and a way to return to setup from login was added to foundry, I'll close this
